main:
  servicename: template
  debugmode: true
  appids: ['2']
  log:
    handlers: ['stdout', 'file']
    levels:
      default: debug
      template: debug
      template.rds: debug
    filename: /tmp/template.log
  request:
    sigkeys:
      '1': 'meleedefaulttestsignaturekeys123'
      '110': 'meleeservertoserversignaturekeys'

  aliyun:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    access_key_id: YWCdSM9iBtjhcRD4
    access_key_secret: LbenstyVqSmr7p6z6r8GuiyYCIFNmJ
    oss:
      config_bucket: hclzconfigdev

  remoteconfig:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    access_key_id: YWCdSM9iBtjhcRD4
    access_key_secret: LbenstyVqSmr7p6z6r8GuiyYCIFNmJ
    bucket_name: hclzconfigdev
    filekeys:
      - servers/product2_dev.yaml
      - servers/products_dev.yaml
      - servers/cshops_dev.yaml
      - servers/dshops_dev.yaml

  imageoss:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    access_key_id: YWCdSM9iBtjhcRD4
    access_key_secret: LbenstyVqSmr7p6z6r8GuiyYCIFNmJ
    bucket_name: hclzimagesdev

  baiduyun:
    ak: 'toZrtVntXNkSjMxNYprKOVlz'

  redis:
    # 主要用来做用户数据分片存储
    # 读写都是分片操作
    key_prefix: template
    instances:
      - redis://192.168.0.11:6379/0
      - redis://192.168.0.11:6379/0

  rediscache:
    test: redis://192.168.0.11:6379/0

  rds:
    pool_config:
      pool_size: 10
    binds:
      order: mysql+pymysql://cshop:cshop1234@hclz.mysql.com:3306/cshop
      cshop: mysql+pymysql://cshop:cshop1234@hclz.mysql.com:3306/cshop
      dshop: mysql+pymysql://cshop:cshop1234@hclz.mysql.com:3306/cshop

  mongodb:
    # 主要用来做用户数据检索，重复写，随机读
    # 写操作将落在以下配置的所有连接实例上
    # 读操作将随机落在以下配置的连接实例上
    # pymongo.mongo_client.MongoClient 的其它初始化参数
    client_options:
      maxPoolSize: 100
      waitQueueTimeoutMS: 100000 #10s
    instances:
      - mongodb://127.0.0.1:27017
      # - mongodb://127.0.0.1:27017

  ccp:
    baseurl: https://app.cloopen.com:8883/2013-12-26
    account_sid: 8a48b5514f4fc588014f5db4b7de1405
    account_token: d7924d01ff174aed9261c0fa5864de69
    app_id: aaf98f89524954cc015253d7658f13dc
    app_token: 2c0bca31a87a34278a9b15e219f483ad

  sms:
    # - {'name': 'neteasesms', 'kwargs': {'baseurl': 'https://api.netease.im', 'appkey': '9a1be2bcfe063aab5b41cff4e7a6bf9c', 'appsecret': '0809de49bd1d'}}
    - {'name': 'yuntongxunsms', 'kwargs': {'baseurl': 'https://app.cloopen.com:8883/2013-12-26', 'account_sid': '8a48b5514f4fc588014f5db4b7de1405', 'account_token': 'd7924d01ff174aed9261c0fa5864de69', 'app_id': 'aaf98f89524954cc015253d7658f13dc', 'app_token': '2c0bca31a87a34278a9b15e219f483ad'}}
  
  email:
    server: smtpdm.aliyun.com
    username: serverop@mail.merben.cc
    password: merben1234

  callbackpays:
    beecloud: 
      - {'appid': '2', 'appID': 'd887281a-ae69-4d93-8f36-527fea8c3d81', 'appSecret': '0162e9e7-5918-45bd-83f3-ab775d592c1e', 'meleeSecret': 'SlEQDSO8RlphzXPC'}


tasklets:
  - {'name': 'demo', 'module': 'melee.tasklets.demotask', 'number': '1', 'args': '3'}

