main:
  servicename: template
  debugmode: true
  log:
    handlers: ['stdout', 'file']
    levels:
      default: debug
      template: debug
      template.rds: debug
    filename: /tmp/template.log
  request:
    sigkeys:
      '1': 'meleedefaulttestsignaturekeys123'
      '110': 'meleeservertoserversignaturekeys'

  aliyun:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    access_key_id: YWCdSM9iBtjhcRD4
    access_key_secret: LbenstyVqSmr7p6z6r8GuiyYCIFNmJ
    oss:
      config: hclzconfigdev

  baiduyun:
    ak: 'toZrtVntXNkSjMxNYprKOVlz'

  redis:
    key_prefix: template
    sharding_threshold: 10000000
    instances:
      - redis://192.168.0.11:6379/0
      - redis://192.168.0.11:6379/0
  rds:
    - mysql://root:hclz1234@hclz.mysql.com:3306/cshop
    - mysql://root:hclz1234@hclz.mysql.com:3306/cshop

  ccp:
    baseurl: https://sandboxapp.cloopen.com:8883/2013-12-26
    account_sid: 8a48b5514f4fc588014f5db4b7de1405
    account_token: d7924d01ff174aed9261c0fa5864de69
    app_id: 8a48b5514f4fc588014f5db52e71140e
    app_token: 0f0616c42d6036e920d2bdb6829c994f

tasklets:
  - {'name': 'demo', 'module': 'melee.tasklets.demotask', 'number': '2', 'args': '1'}
