main:
  servicename: template
  log:
    handlers: ['stdout', 'file']
    levels:
      default: debug
      template: debug
      template.rds: debug
    filename: /tmp/template.log
  request:
    sigkeys:
      '1': 'meleedefaulttestsignaturekeys123'
      '110': 'meleeservertoserversignaturekeys'
